Escalares

In [2]:
import numpy as np
escalar = np.array(42)
print(escalar)
print(type(escalar))

42
<class 'numpy.ndarray'>


Vectores

In [3]:
vector = np.array([30, 29, 35, 31, 33, 36, 42])
print(vector)

[30 29 35 31 33 36 42]


Matriz

In [4]:
matrix = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Tensores

In [5]:
tensor = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


Aranges

In [6]:
array_arange = np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


Matriz Identidad

In [9]:
eye_matrix = np.eye(6)
print(eye_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Matriz Diagonal

In [11]:
diag = np.diag([1, 2, 3, 4, 5, 6, 7])
print(diag)

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


Random

In [14]:
random = np.random.random((2, 3))
print(random)

[[0.76268065 0.42052203 0.39420656]
 [0.22973272 0.20898837 0.15487864]]
