Suma de matrices

In [1]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

suma = A + B
print(suma)

[[ 6  8]
 [10 12]]


Multiplicacion de matrices

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

producto = np.dot(A, B)
print(producto)

[[19 22]
 [43 50]]


Transposicion de Matrices

In [8]:
A = np.array([[1, 2], [3, 4]])
print(A)
print()

transpuesta = A.transpose()
print(transpuesta)

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


Determinante de una matriz

In [9]:
A = np.array([[1, 2], [3, 4]])
determinante = np.linalg.det(A)
print("Determinante de A: ", determinante)

Determinante de A:  -2.0000000000000004


Matriz inversa de A

In [10]:
inversa = np.linalg.inv(A)
print("Inversa de A: \n", inversa)

Inversa de A: 
 [[-2.   1. ]
 [ 1.5 -0.5]]
