Instrucción: Crea dos arrays de 1D con valores enteros y realiza las operaciones de suma, resta, multiplicación, y división entre ellos.

In [6]:
import numpy as np

array1 = np.array([10, 20, 30, 40])
array2 = np.array([1, 2, 3, 4])

suma = array1 + array2
resta = array1 - array2
multiplicacion = array1 * array2
division = array1 / array2

print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)
print("División:", division)

Suma: [11 22 33 44]
Resta: [ 9 18 27 36]
Multiplicación: [ 10  40  90 160]
División: [10. 10. 10. 10.]


Dado un array de datos, calcula la media, mediana, varianza, y desviación estándar.

In [12]:
datos = np.array([23, 76, 35, 67, 89, 45, 68, 79, 35])

media = np.mean(datos)
mediana = np.median(datos)
varianza = np.var(datos)
desviacion_std = np.std(datos)

print(f"Media del data set: {media}")
print(f"Media del data set: {mediana}")
print(f"Media del data set: {varianza}")
print(f"Desviacion estandar: {desviacion_std}")

Media del data set: 57.44444444444444
Media del data set: 67.0
Media del data set: 484.02469135802465
Desviacion estandar: 22.000561160071


Crea dos matrices de 2x2 y realiza las operaciones de suma, resta, multiplicación (producto matricial) y cálculo de la inversa de una de ellas.

In [24]:
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

suma_matricial = matriz1 + matriz2
resta_matricial = matriz1 - matriz2
multiplicacion = matriz1 * matriz2
inversa = np.linalg.inv(matriz1)

print(matriz1)
print("Suma matricial es: \n", suma_matricial)
print("Resta matricial es: \n", resta_matricial)
print("Producto matricial (multiplicacion) es: \n", multiplicacion)
print("La inversa de la matriz 1 es: \n", inversa)

[[1 2]
 [3 4]]
Suma matricial es: 
 [[ 6  8]
 [10 12]]
Resta matricial es: 
 [[-4 -4]
 [-4 -4]]
Producto matricial (multiplicacion) es: 
 [[ 5 12]
 [21 32]]
La inversa de la matriz 1 es: 
 [[-2.   1. ]
 [ 1.5 -0.5]]


Ejercicio 4. Resuelve el sistema de ecuaciones lineales dado por Ax=b, donde A es una matriz 2x2 y b es un vector de 2 elementos. Ax=bAx = b

In [4]:
import numpy as np

A = np.array([[2, 3], [1, 2]])
b = np.array([8, 5])

x = np.linalg.solve(A, b)
print("solucion del sistem de ecuaciones: ", x)

solucion del sistem de ecuaciones:  [1. 2.]
