Broadcasting

In [1]:
import numpy as np

Multiplicando un array grande con un array de un valor

In [2]:
prices = np.array([100, 200, 300])
discount = np.array([0.9])
discount_prices = prices * discount
print(discount_prices)

[ 90. 180. 270.]


Sumando un array grande con otro array

In [3]:
prices = np.random.randint(100, 500, size=(3,3))
discount = np.array([10, 20, 30])
discount_prices = prices + discount
print(prices)
print(discount_prices)

[[106 138 394]
 [316 218 420]
 [267 444 359]]
[[116 158 424]
 [326 238 450]
 [277 464 389]]


Operaciones logicas con array

In [5]:
array = np.array([1, 2, 3, 4, 5])
print(np.all(array > 0))
print(np.all(array > 9))
print(np.all(array > 3))

True
False
False


In [7]:
print(np.any(array > 3))
print(np.any(array > 9))
print(np.any(array > 0))

True
False
True


Concatenacion de arrays

In [9]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
concatenated_a = np.concatenate((array_a, array_a))
concatenated_ab = np.concatenate((array_a, array_b))
print(concatenated_a)
print(concatenated_ab)

[1 2 3 1 2 3]
[1 2 3 4 5 6]


Stacking arrays Vertical

In [10]:
stacked_v = np.vstack((array_a, array_b))
print(stacked_v)

[[1 2 3]
 [4 5 6]]


Stacking arrays Horizontal

In [11]:
stacked_h = np.hstack((array_a, array_b))
print(stacked_h)

[1 2 3 4 5 6]


Division o Split de arrays

In [13]:
array_c = np.arange(1, 10)
split_array = np.split(array_c, 3)
print(array_c)
print(split_array)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
