Unique

In [1]:
import numpy as np

In [4]:
survey_responses = np.array([
    "bueno", "excelente", "malo",
    "bueno", "malo", "excelente",
    "bueno", "bueno", "malo",
    "excelente", "regular"
])


In [5]:
print(np.unique(survey_responses))

['bueno' 'excelente' 'malo' 'regular']


Contando los valores de dataset

In [7]:
unique_elements, counts = np.unique(survey_responses, return_counts=True)
print(unique_elements, counts)

['bueno' 'excelente' 'malo' 'regular'] [4 3 3 1]


Funcionamiento de las Vistas

In [11]:
array_x = np.arange(10)
view_y = array_x[1:3]
print(array_x)
print(view_y)
array_x[1:3] = [10, 20]
print(array_x)
print(view_y) # Esta vista sigue apuntando al array_x antiguo

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 20  3  4  5  6  7  8  9]
[10 20]


In [12]:
array_x = np.arange(10)
copy_x = array_x[[1, 2]]
print(array_x)
print(copy_x)
array_x[1:3] = [10, 20]
print(array_x)
print(copy_x)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 20  3  4  5  6  7  8  9]
[1 2]
