In [2]:
import numpy as np

Accediendo a valores de un array

In [3]:
array = np.array([10, 20, 30, 40, 50])
print(array[1])
print(array[-1])

20
50


Accediendo a subconjuntos

In [4]:
print(array[1:4])

[20 30 40]


In [5]:
print(array[1:7])

[20 30 40 50]


In [6]:
print(array[-1:-7])

[]


Indexacion Booleana

In [9]:
array = np.array([10, 20, 30, 40, 50])
bool_index = array > 25
print(bool_index)
print(type(bool_index))

[False False  True  True  True]
<class 'numpy.ndarray'>


Imprimiendo usando los indices de un Array

In [11]:
index = [2, 0, 4]
print(array[index])

[30 10 50]


Generando un array con numeros random matriz 3x3

In [15]:
array = np.random.randint(1, 10, size=(3,3))
print(array)
print(array[0, 1])

[[2 8 3]
 [7 7 8]
 [9 4 1]]
8


Extrayendo parte de los valores de una matriz

In [16]:
print(array[:2,:2])

[[2 8]
 [7 7]]
