Transformacion de Arrays

In [1]:
import numpy as np

In [2]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
transposed_matrix = matrix.T
print(matrix)
print(transposed_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


Reshape

In [3]:
array = np.arange(1, 13)
reshaped_array = array.reshape(3, 4)
print(array)
print(reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Invertir un array

In [4]:
reversed_array = array[::-1]
print(array)
print(reversed_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[12 11 10  9  8  7  6  5  4  3  2  1]


In [6]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flattened_array = matrix.flatten()
print(matrix)
print(flattened_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
